export interface Shoe {
  id: string;
  name: string;
  brand: string;
  price: number;
  originalPrice: number;
  image: string;
  description: string;
  category: string;
  gender: string;
  colors: string[];
  sizes: number[];
  rating: number;
  reviews: number;
  stock: number;
}

export const SHOES: Shoe[] = [

  // --- NIKE (10) ---
  { 
    id: 'n1', 
    name: 'dunk-low-retro', 
    brand: 'Nike', 
    price: Math.floor(Math.random() * (20000 - 6000) + 6000), 
    originalPrice: Math.floor(Math.random() * (25000 - 8000) + 8000), 
    image: 'https://res.cloudinary.com/des0lvjl7/image/upload/v1772206843/sneaker-store/nike/sneaker-store/nike/dunk-low-retro.jpg', 
    description: 'Premium Nike sneaker', 
    category: 'Lifestyle', 
    gender: 'Unisex', 
    colors: ['Default'], 
    sizes: [6, 7, 8, 9, 10, 11], 
    rating: 4.5 + Math.random() * 0.5, 
    reviews: Math.floor(Math.random() * 5000), 
    stock: Math.floor(Math.random() * 50) + 5 
  },
  { 
    id: 'n2', 
    name: 'nike-air-force-1-low', 
    brand: 'Nike', 
    price: Math.floor(Math.random() * (20000 - 6000) + 6000), 
    originalPrice: Math.floor(Math.random() * (25000 - 8000) + 8000), 
    image: 'https://res.cloudinary.com/des0lvjl7/image/upload/v1772206845/sneaker-store/nike/sneaker-store/nike/nike-air-force-1-low.jpg', 
    description: 'Premium Nike sneaker', 
    category: 'Lifestyle', 
    gender: 'Unisex', 
    colors: ['Default'], 
    sizes: [6, 7, 8, 9, 10, 11], 
    rating: 4.5 + Math.random() * 0.5, 
    reviews: Math.floor(Math.random() * 5000), 
    stock: Math.floor(Math.random() * 50) + 5 
  },
  { 
    id: 'n3', 
    name: 'nike-air-jordan-1-low', 
    brand: 'Nike', 
    price: Math.floor(Math.random() * (20000 - 6000) + 6000), 
    originalPrice: Math.floor(Math.random() * (25000 - 8000) + 8000), 
    image: 'https://res.cloudinary.com/des0lvjl7/image/upload/v1772206846/sneaker-store/nike/sneaker-store/nike/nike-air-jordan-1-low.jpg', 
    description: 'Premium Nike sneaker', 
    category: 'Lifestyle', 
    gender: 'Unisex', 
    colors: ['Default'], 
    sizes: [6, 7, 8, 9, 10, 11], 
    rating: 4.5 + Math.random() * 0.5, 
    reviews: Math.floor(Math.random() * 5000), 
    stock: Math.floor(Math.random() * 50) + 5 
  },
  { 
    id: 'n4', 
    name: 'nike-air-max-270', 
    brand: 'Nike', 
    price: Math.floor(Math.random() * (20000 - 6000) + 6000), 
    originalPrice: Math.floor(Math.random() * (25000 - 8000) + 8000), 
    image: 'https://res.cloudinary.com/des0lvjl7/image/upload/v1772206847/sneaker-store/nike/sneaker-store/nike/nike-air-max-270.jpg', 
    description: 'Premium Nike sneaker', 
    category: 'Lifestyle', 
    gender: 'Unisex', 
    colors: ['Default'], 
    sizes: [6, 7, 8, 9, 10, 11], 
    rating: 4.5 + Math.random() * 0.5, 
    reviews: Math.floor(Math.random() * 5000), 
    stock: Math.floor(Math.random() * 50) + 5 
  },
  { 
    id: 'n5', 
    name: 'nike-air-max-90-essentials', 
    brand: 'Nike', 
    price: Math.floor(Math.random() * (20000 - 6000) + 6000), 
    originalPrice: Math.floor(Math.random() * (25000 - 8000) + 8000), 
    image: 'https://res.cloudinary.com/des0lvjl7/image/upload/v1772206848/sneaker-store/nike/sneaker-store/nike/nike-air-max-90-essentials.jpg', 
    description: 'Premium Nike sneaker', 
    category: 'Lifestyle', 
    gender: 'Unisex', 
    colors: ['Default'], 
    sizes: [6, 7, 8, 9, 10, 11], 
    rating: 4.5 + Math.random() * 0.5, 
    reviews: Math.floor(Math.random() * 5000), 
    stock: Math.floor(Math.random() * 50) + 5 
  },
  { 
    id: 'n6', 
    name: 'nike-air-max-97', 
    brand: 'Nike', 
    price: Math.floor(Math.random() * (20000 - 6000) + 6000), 
    originalPrice: Math.floor(Math.random() * (25000 - 8000) + 8000), 
    image: 'https://res.cloudinary.com/des0lvjl7/image/upload/v1772206850/sneaker-store/nike/sneaker-store/nike/nike-air-max-97.jpg', 
    description: 'Premium Nike sneaker', 
    category: 'Lifestyle', 
    gender: 'Unisex', 
    colors: ['Default'], 
    sizes: [6, 7, 8, 9, 10, 11], 
    rating: 4.5 + Math.random() * 0.5, 
    reviews: Math.floor(Math.random() * 5000), 
    stock: Math.floor(Math.random() * 50) + 5 
  },
  { 
    id: 'n7', 
    name: 'nike-blazer-mid-77', 
    brand: 'Nike', 
    price: Math.floor(Math.random() * (20000 - 6000) + 6000), 
    originalPrice: Math.floor(Math.random() * (25000 - 8000) + 8000), 
    image: 'https://res.cloudinary.com/des0lvjl7/image/upload/v1772206851/sneaker-store/nike/sneaker-store/nike/nike-blazer-mid-77.jpg', 
    description: 'Premium Nike sneaker', 
    category: 'Lifestyle', 
    gender: 'Unisex', 
    colors: ['Default'], 
    sizes: [6, 7, 8, 9, 10, 11], 
    rating: 4.5 + Math.random() * 0.5, 
    reviews: Math.floor(Math.random() * 5000), 
    stock: Math.floor(Math.random() * 50) + 5 
  },
  { 
    id: 'n8', 
    name: 'nike-metcon-9', 
    brand: 'Nike', 
    price: Math.floor(Math.random() * (20000 - 6000) + 6000), 
    originalPrice: Math.floor(Math.random() * (25000 - 8000) + 8000), 
    image: 'https://res.cloudinary.com/des0lvjl7/image/upload/v1772206853/sneaker-store/nike/sneaker-store/nike/nike-metcon-9.jpg', 
    description: 'Premium Nike sneaker', 
    category: 'Lifestyle', 
    gender: 'Unisex', 
    colors: ['Default'], 
    sizes: [6, 7, 8, 9, 10, 11], 
    rating: 4.5 + Math.random() * 0.5, 
    reviews: Math.floor(Math.random() * 5000), 
    stock: Math.floor(Math.random() * 50) + 5 
  },
  { 
    id: 'n9', 
    name: 'nike-vaporfly-3', 
    brand: 'Nike', 
    price: Math.floor(Math.random() * (20000 - 6000) + 6000), 
    originalPrice: Math.floor(Math.random() * (25000 - 8000) + 8000), 
    image: 'https://res.cloudinary.com/des0lvjl7/image/upload/v1772206853/sneaker-store/nike/sneaker-store/nike/nike-vaporfly-3.jpg', 
    description: 'Premium Nike sneaker', 
    category: 'Lifestyle', 
    gender: 'Unisex', 
    colors: ['Default'], 
    sizes: [6, 7, 8, 9, 10, 11], 
    rating: 4.5 + Math.random() * 0.5, 
    reviews: Math.floor(Math.random() * 5000), 
    stock: Math.floor(Math.random() * 50) + 5 
  },
  { 
    id: 'n10', 
    name: 'nike-zoom-vomero-5', 
    brand: 'Nike', 
    price: Math.floor(Math.random() * (20000 - 6000) + 6000), 
    originalPrice: Math.floor(Math.random() * (25000 - 8000) + 8000), 
    image: 'https://res.cloudinary.com/des0lvjl7/image/upload/v1772206854/sneaker-store/nike/sneaker-store/nike/nike-zoom-vomero-5.jpg', 
    description: 'Premium Nike sneaker', 
    category: 'Lifestyle', 
    gender: 'Unisex', 
    colors: ['Default'], 
    sizes: [6, 7, 8, 9, 10, 11], 
    rating: 4.5 + Math.random() * 0.5, 
    reviews: Math.floor(Math.random() * 5000), 
    stock: Math.floor(Math.random() * 50) + 5 
  },

  // --- ADIDAS (10) ---
  { 
    id: 'a11', 
    name: 'addidas-nmd_r1-v3', 
    brand: 'Adidas', 
    price: Math.floor(Math.random() * (20000 - 6000) + 6000), 
    originalPrice: Math.floor(Math.random() * (25000 - 8000) + 8000), 
    image: 'https://res.cloudinary.com/des0lvjl7/image/upload/v1772206855/sneaker-store/addidas/sneaker-store/addidas/addidas-nmd_r1-v3.jpg', 
    description: 'Premium Adidas sneaker', 
    category: 'Lifestyle', 
    gender: 'Unisex', 
    colors: ['Default'], 
    sizes: [6, 7, 8, 9, 10, 11], 
    rating: 4.5 + Math.random() * 0.5, 
    reviews: Math.floor(Math.random() * 5000), 
    stock: Math.floor(Math.random() * 50) + 5 
  },
  { 
    id: 'a12', 
    name: 'addidas-stan-smith-lux', 
    brand: 'Adidas', 
    price: Math.floor(Math.random() * (20000 - 6000) + 6000), 
    originalPrice: Math.floor(Math.random() * (25000 - 8000) + 8000), 
    image: 'https://res.cloudinary.com/des0lvjl7/image/upload/v1772206856/sneaker-store/addidas/sneaker-store/addidas/addidas-stan-smith-lux.jpg', 
    description: 'Premium Adidas sneaker', 
    category: 'Lifestyle', 
    gender: 'Unisex', 
    colors: ['Default'], 
    sizes: [6, 7, 8, 9, 10, 11], 
    rating: 4.5 + Math.random() * 0.5, 
    reviews: Math.floor(Math.random() * 5000), 
    stock: Math.floor(Math.random() * 50) + 5 
  },
  { 
    id: 'a13', 
    name: 'addidas-ultraboost-light', 
    brand: 'Adidas', 
    price: Math.floor(Math.random() * (20000 - 6000) + 6000), 
    originalPrice: Math.floor(Math.random() * (25000 - 8000) + 8000), 
    image: 'https://res.cloudinary.com/des0lvjl7/image/upload/v1772206857/sneaker-store/addidas/sneaker-store/addidas/addidas-ultraboost-light.jpg', 
    description: 'Premium Adidas sneaker', 
    category: 'Lifestyle', 
    gender: 'Unisex', 
    colors: ['Default'], 
    sizes: [6, 7, 8, 9, 10, 11], 
    rating: 4.5 + Math.random() * 0.5, 
    reviews: Math.floor(Math.random() * 5000), 
    stock: Math.floor(Math.random() * 50) + 5 
  },
  { 
    id: 'a14', 
    name: 'adizero-pro-3', 
    brand: 'Adidas', 
    price: Math.floor(Math.random() * (20000 - 6000) + 6000), 
    originalPrice: Math.floor(Math.random() * (25000 - 8000) + 8000), 
    image: 'https://res.cloudinary.com/des0lvjl7/image/upload/v1772206858/sneaker-store/addidas/sneaker-store/addidas/adizero-pro-3.jpg', 
    description: 'Premium Adidas sneaker', 
    category: 'Lifestyle', 
    gender: 'Unisex', 
    colors: ['Default'], 
    sizes: [6, 7, 8, 9, 10, 11], 
    rating: 4.5 + Math.random() * 0.5, 
    reviews: Math.floor(Math.random() * 5000), 
    stock: Math.floor(Math.random() * 50) + 5 
  },
  { 
    id: 'a15', 
    name: 'campus-oo', 
    brand: 'Adidas', 
    price: Math.floor(Math.random() * (20000 - 6000) + 6000), 
    originalPrice: Math.floor(Math.random() * (25000 - 8000) + 8000), 
    image: 'https://res.cloudinary.com/des0lvjl7/image/upload/v1772206859/sneaker-store/addidas/sneaker-store/addidas/campus-oo.jpg', 
    description: 'Premium Adidas sneaker', 
    category: 'Lifestyle', 
    gender: 'Unisex', 
    colors: ['Default'], 
    sizes: [6, 7, 8, 9, 10, 11], 
    rating: 4.5 + Math.random() * 0.5, 
    reviews: Math.floor(Math.random() * 5000), 
    stock: Math.floor(Math.random() * 50) + 5 
  },
  { 
    id: 'a16', 
    name: 'forum-low', 
    brand: 'Adidas', 
    price: Math.floor(Math.random() * (20000 - 6000) + 6000), 
    originalPrice: Math.floor(Math.random() * (25000 - 8000) + 8000), 
    image: 'https://res.cloudinary.com/des0lvjl7/image/upload/v1772206860/sneaker-store/addidas/sneaker-store/addidas/forum-low.jpg', 
    description: 'Premium Adidas sneaker', 
    category: 'Lifestyle', 
    gender: 'Unisex', 
    colors: ['Default'], 
    sizes: [6, 7, 8, 9, 10, 11], 
    rating: 4.5 + Math.random() * 0.5, 
    reviews: Math.floor(Math.random() * 5000), 
    stock: Math.floor(Math.random() * 50) + 5 
  },
  { 
    id: 'a17', 
    name: 'gazelle-indoor', 
    brand: 'Adidas', 
    price: Math.floor(Math.random() * (20000 - 6000) + 6000), 
    originalPrice: Math.floor(Math.random() * (25000 - 8000) + 8000), 
    image: 'https://res.cloudinary.com/des0lvjl7/image/upload/v1772206861/sneaker-store/addidas/sneaker-store/addidas/gazelle-indoor.jpg', 
    description: 'Premium Adidas sneaker', 
    category: 'Lifestyle', 
    gender: 'Unisex', 
    colors: ['Default'], 
    sizes: [6, 7, 8, 9, 10, 11], 
    rating: 4.5 + Math.random() * 0.5, 
    reviews: Math.floor(Math.random() * 5000), 
    stock: Math.floor(Math.random() * 50) + 5 
  },
  { 
    id: 'a18', 
    name: 'handball-specail', 
    brand: 'Adidas', 
    price: Math.floor(Math.random() * (20000 - 6000) + 6000), 
    originalPrice: Math.floor(Math.random() * (25000 - 8000) + 8000), 
    image: 'https://res.cloudinary.com/des0lvjl7/image/upload/v1772206862/sneaker-store/addidas/sneaker-store/addidas/handball-specail.jpg', 
    description: 'Premium Adidas sneaker', 
    category: 'Lifestyle', 
    gender: 'Unisex', 
    colors: ['Default'], 
    sizes: [6, 7, 8, 9, 10, 11], 
    rating: 4.5 + Math.random() * 0.5, 
    reviews: Math.floor(Math.random() * 5000), 
    stock: Math.floor(Math.random() * 50) + 5 
  },
  { 
    id: 'a19', 
    name: 'superstar-xlg', 
    brand: 'Adidas', 
    price: Math.floor(Math.random() * (20000 - 6000) + 6000), 
    originalPrice: Math.floor(Math.random() * (25000 - 8000) + 8000), 
    image: 'https://res.cloudinary.com/des0lvjl7/image/upload/v1772206864/sneaker-store/addidas/sneaker-store/addidas/superstar-xlg.jpg', 
    description: 'Premium Adidas sneaker', 
    category: 'Lifestyle', 
    gender: 'Unisex', 
    colors: ['Default'], 
    sizes: [6, 7, 8, 9, 10, 11], 
    rating: 4.5 + Math.random() * 0.5, 
    reviews: Math.floor(Math.random() * 5000), 
    stock: Math.floor(Math.random() * 50) + 5 
  },
  { 
    id: 'a20', 
    name: 'ultraboost-light', 
    brand: 'Adidas', 
    price: Math.floor(Math.random() * (20000 - 6000) + 6000), 
    originalPrice: Math.floor(Math.random() * (25000 - 8000) + 8000), 
    image: 'https://res.cloudinary.com/des0lvjl7/image/upload/v1772206872/sneaker-store/addidas/sneaker-store/addidas/ultraboost-light.jpg', 
    description: 'Premium Adidas sneaker', 
    category: 'Lifestyle', 
    gender: 'Unisex', 
    colors: ['Default'], 
    sizes: [6, 7, 8, 9, 10, 11], 
    rating: 4.5 + Math.random() * 0.5, 
    reviews: Math.floor(Math.random() * 5000), 
    stock: Math.floor(Math.random() * 50) + 5 
  },

  // --- ASICS (10) ---
  { 
    id: 'A21', 
    name: 'asics-ex89-basketball', 
    brand: 'Asics', 
    price: Math.floor(Math.random() * (20000 - 6000) + 6000), 
    originalPrice: Math.floor(Math.random() * (25000 - 8000) + 8000), 
    image: 'https://res.cloudinary.com/des0lvjl7/image/upload/v1772206873/sneaker-store/Asics/sneaker-store/Asics/asics-ex89-basketball.png', 
    description: 'Premium Asics sneaker', 
    category: 'Lifestyle', 
    gender: 'Unisex', 
    colors: ['Default'], 
    sizes: [6, 7, 8, 9, 10, 11], 
    rating: 4.5 + Math.random() * 0.5, 
    reviews: Math.floor(Math.random() * 5000), 
    stock: Math.floor(Math.random() * 50) + 5 
  },
  { 
    id: 'A22', 
    name: 'asics-gel-1130-silver', 
    brand: 'Asics', 
    price: Math.floor(Math.random() * (20000 - 6000) + 6000), 
    originalPrice: Math.floor(Math.random() * (25000 - 8000) + 8000), 
    image: 'https://res.cloudinary.com/des0lvjl7/image/upload/v1772206874/sneaker-store/Asics/sneaker-store/Asics/asics-gel-1130-silver.jpg', 
    description: 'Premium Asics sneaker', 
    category: 'Lifestyle', 
    gender: 'Unisex', 
    colors: ['Default'], 
    sizes: [6, 7, 8, 9, 10, 11], 
    rating: 4.5 + Math.random() * 0.5, 
    reviews: Math.floor(Math.random() * 5000), 
    stock: Math.floor(Math.random() * 50) + 5 
  },
  { 
    id: 'A23', 
    name: 'asics-gel-kayano-30', 
    brand: 'Asics', 
    price: Math.floor(Math.random() * (20000 - 6000) + 6000), 
    originalPrice: Math.floor(Math.random() * (25000 - 8000) + 8000), 
    image: 'https://res.cloudinary.com/des0lvjl7/image/upload/v1772206876/sneaker-store/Asics/sneaker-store/Asics/asics-gel-kayano-30.jpg', 
    description: 'Premium Asics sneaker', 
    category: 'Lifestyle', 
    gender: 'Unisex', 
    colors: ['Default'], 
    sizes: [6, 7, 8, 9, 10, 11], 
    rating: 4.5 + Math.random() * 0.5, 
    reviews: Math.floor(Math.random() * 5000), 
    stock: Math.floor(Math.random() * 50) + 5 
  },
  { 
    id: 'A24', 
    name: 'asics-gel-lyte-3', 
    brand: 'Asics', 
    price: Math.floor(Math.random() * (20000 - 6000) + 6000), 
    originalPrice: Math.floor(Math.random() * (25000 - 8000) + 8000), 
    image: 'https://res.cloudinary.com/des0lvjl7/image/upload/v1772206877/sneaker-store/Asics/sneaker-store/Asics/asics-gel-lyte-3.jpg', 
    description: 'Premium Asics sneaker', 
    category: 'Lifestyle', 
    gender: 'Unisex', 
    colors: ['Default'], 
    sizes: [6, 7, 8, 9, 10, 11], 
    rating: 4.5 + Math.random() * 0.5, 
    reviews: Math.floor(Math.random() * 5000), 
    stock: Math.floor(Math.random() * 50) + 5 
  },
  { 
    id: 'A25', 
    name: 'asics-gel-nimbus-26', 
    brand: 'Asics', 
    price: Math.floor(Math.random() * (20000 - 6000) + 6000), 
    originalPrice: Math.floor(Math.random() * (25000 - 8000) + 8000), 
    image: 'https://res.cloudinary.com/des0lvjl7/image/upload/v1772206878/sneaker-store/Asics/sneaker-store/Asics/asics-gel-nimbus-26.jpg', 
    description: 'Premium Asics sneaker', 
    category: 'Lifestyle', 
    gender: 'Unisex', 
    colors: ['Default'], 
    sizes: [6, 7, 8, 9, 10, 11], 
    rating: 4.5 + Math.random() * 0.5, 
    reviews: Math.floor(Math.random() * 5000), 
    stock: Math.floor(Math.random() * 50) + 5 
  },
  { 
    id: 'A26', 
    name: 'asics-gel-nyc-cream', 
    brand: 'Asics', 
    price: Math.floor(Math.random() * (20000 - 6000) + 6000), 
    originalPrice: Math.floor(Math.random() * (25000 - 8000) + 8000), 
    image: 'https://res.cloudinary.com/des0lvjl7/image/upload/v1772206879/sneaker-store/Asics/sneaker-store/Asics/asics-gel-nyc-cream.jpg', 
    description: 'Premium Asics sneaker', 
    category: 'Lifestyle', 
    gender: 'Unisex', 
    colors: ['Default'], 
    sizes: [6, 7, 8, 9, 10, 11], 
    rating: 4.5 + Math.random() * 0.5, 
    reviews: Math.floor(Math.random() * 5000), 
    stock: Math.floor(Math.random() * 50) + 5 
  },
  { 
    id: 'A27', 
    name: 'asics-gel-quantum-360', 
    brand: 'Asics', 
    price: Math.floor(Math.random() * (20000 - 6000) + 6000), 
    originalPrice: Math.floor(Math.random() * (25000 - 8000) + 8000), 
    image: 'https://res.cloudinary.com/des0lvjl7/image/upload/v1772206880/sneaker-store/Asics/sneaker-store/Asics/asics-gel-quantum-360.jpg', 
    description: 'Premium Asics sneaker', 
    category: 'Lifestyle', 
    gender: 'Unisex', 
    colors: ['Default'], 
    sizes: [6, 7, 8, 9, 10, 11], 
    rating: 4.5 + Math.random() * 0.5, 
    reviews: Math.floor(Math.random() * 5000), 
    stock: Math.floor(Math.random() * 50) + 5 
  },
  { 
    id: 'A28', 
    name: 'asics-gel-resolution-9', 
    brand: 'Asics', 
    price: Math.floor(Math.random() * (20000 - 6000) + 6000), 
    originalPrice: Math.floor(Math.random() * (25000 - 8000) + 8000), 
    image: 'https://res.cloudinary.com/des0lvjl7/image/upload/v1772206881/sneaker-store/Asics/sneaker-store/Asics/asics-gel-resolution-9.jpg', 
    description: 'Premium Asics sneaker', 
    category: 'Lifestyle', 
    gender: 'Unisex', 
    colors: ['Default'], 
    sizes: [6, 7, 8, 9, 10, 11], 
    rating: 4.5 + Math.random() * 0.5, 
    reviews: Math.floor(Math.random() * 5000), 
    stock: Math.floor(Math.random() * 50) + 5 
  },
  { 
    id: 'A29', 
    name: 'asics-gt2160-gold', 
    brand: 'Asics', 
    price: Math.floor(Math.random() * (20000 - 6000) + 6000), 
    originalPrice: Math.floor(Math.random() * (25000 - 8000) + 8000), 
    image: 'https://res.cloudinary.com/des0lvjl7/image/upload/v1772206882/sneaker-store/Asics/sneaker-store/Asics/asics-gt2160-gold.jpg', 
    description: 'Premium Asics sneaker', 
    category: 'Lifestyle', 
    gender: 'Unisex', 
    colors: ['Default'], 
    sizes: [6, 7, 8, 9, 10, 11], 
    rating: 4.5 + Math.random() * 0.5, 
    reviews: Math.floor(Math.random() * 5000), 
    stock: Math.floor(Math.random() * 50) + 5 
  },
  { 
    id: 'A30', 
    name: 'asics-novablast-4', 
    brand: 'Asics', 
    price: Math.floor(Math.random() * (20000 - 6000) + 6000), 
    originalPrice: Math.floor(Math.random() * (25000 - 8000) + 8000), 
    image: 'https://res.cloudinary.com/des0lvjl7/image/upload/v1772206883/sneaker-store/Asics/sneaker-store/Asics/asics-novablast-4.jpg', 
    description: 'Premium Asics sneaker', 
    category: 'Lifestyle', 
    gender: 'Unisex', 
    colors: ['Default'], 
    sizes: [6, 7, 8, 9, 10, 11], 
    rating: 4.5 + Math.random() * 0.5, 
    reviews: Math.floor(Math.random() * 5000), 
    stock: Math.floor(Math.random() * 50) + 5 
  },

  // --- JORDAN (10) ---
  { 
    id: 'j31', 
    name: 'air-jordan-1-high', 
    brand: 'Jordan', 
    price: Math.floor(Math.random() * (20000 - 6000) + 6000), 
    originalPrice: Math.floor(Math.random() * (25000 - 8000) + 8000), 
    image: 'https://res.cloudinary.com/des0lvjl7/image/upload/v1772206884/sneaker-store/jordan/sneaker-store/jordan/air-jordan-1-high.jpg', 
    description: 'Premium Jordan sneaker', 
    category: 'Lifestyle', 
    gender: 'Unisex', 
    colors: ['Default'], 
    sizes: [6, 7, 8, 9, 10, 11], 
    rating: 4.5 + Math.random() * 0.5, 
    reviews: Math.floor(Math.random() * 5000), 
    stock: Math.floor(Math.random() * 50) + 5 
  },
  { 
    id: 'j32', 
    name: 'air-jordan-white-cement', 
    brand: 'Jordan', 
    price: Math.floor(Math.random() * (20000 - 6000) + 6000), 
    originalPrice: Math.floor(Math.random() * (25000 - 8000) + 8000), 
    image: 'https://res.cloudinary.com/des0lvjl7/image/upload/v1772206885/sneaker-store/jordan/sneaker-store/jordan/air-jordan-white-cement.jpg', 
    description: 'Premium Jordan sneaker', 
    category: 'Lifestyle', 
    gender: 'Unisex', 
    colors: ['Default'], 
    sizes: [6, 7, 8, 9, 10, 11], 
    rating: 4.5 + Math.random() * 0.5, 
    reviews: Math.floor(Math.random() * 5000), 
    stock: Math.floor(Math.random() * 50) + 5 
  },
  { 
    id: 'j33', 
    name: 'jordan-air-jordan-1-high', 
    brand: 'Jordan', 
    price: Math.floor(Math.random() * (20000 - 6000) + 6000), 
    originalPrice: Math.floor(Math.random() * (25000 - 8000) + 8000), 
    image: 'https://res.cloudinary.com/des0lvjl7/image/upload/v1772206886/sneaker-store/jordan/sneaker-store/jordan/jordan-air-jordan-1-high.jpg', 
    description: 'Premium Jordan sneaker', 
    category: 'Lifestyle', 
    gender: 'Unisex', 
    colors: ['Default'], 
    sizes: [6, 7, 8, 9, 10, 11], 
    rating: 4.5 + Math.random() * 0.5, 
    reviews: Math.floor(Math.random() * 5000), 
    stock: Math.floor(Math.random() * 50) + 5 
  },
  { 
    id: 'j34', 
    name: 'jordan-air-jordan-11-concord', 
    brand: 'Jordan', 
    price: Math.floor(Math.random() * (20000 - 6000) + 6000), 
    originalPrice: Math.floor(Math.random() * (25000 - 8000) + 8000), 
    image: 'https://res.cloudinary.com/des0lvjl7/image/upload/v1772206886/sneaker-store/jordan/sneaker-store/jordan/jordan-air-jordan-11-concord.jpg', 
    description: 'Premium Jordan sneaker', 
    category: 'Lifestyle', 
    gender: 'Unisex', 
    colors: ['Default'], 
    sizes: [6, 7, 8, 9, 10, 11], 
    rating: 4.5 + Math.random() * 0.5, 
    reviews: Math.floor(Math.random() * 5000), 
    stock: Math.floor(Math.random() * 50) + 5 
  },
  { 
    id: 'j35', 
    name: 'jordan-air-jordan-13-bred', 
    brand: 'Jordan', 
    price: Math.floor(Math.random() * (20000 - 6000) + 6000), 
    originalPrice: Math.floor(Math.random() * (25000 - 8000) + 8000), 
    image: 'https://res.cloudinary.com/des0lvjl7/image/upload/v1772206887/sneaker-store/jordan/sneaker-store/jordan/jordan-air-jordan-13-bred.jpg', 
    description: 'Premium Jordan sneaker', 
    category: 'Lifestyle', 
    gender: 'Unisex', 
    colors: ['Default'], 
    sizes: [6, 7, 8, 9, 10, 11], 
    rating: 4.5 + Math.random() * 0.5, 
    reviews: Math.floor(Math.random() * 5000), 
    stock: Math.floor(Math.random() * 50) + 5 
  },
  { 
    id: 'j36', 
    name: 'jordan-air-jordan-4-bred', 
    brand: 'Jordan', 
    price: Math.floor(Math.random() * (20000 - 6000) + 6000), 
    originalPrice: Math.floor(Math.random() * (25000 - 8000) + 8000), 
    image: 'https://res.cloudinary.com/des0lvjl7/image/upload/v1772206888/sneaker-store/jordan/sneaker-store/jordan/jordan-air-jordan-4-bred.jpg', 
    description: 'Premium Jordan sneaker', 
    category: 'Lifestyle', 
    gender: 'Unisex', 
    colors: ['Default'], 
    sizes: [6, 7, 8, 9, 10, 11], 
    rating: 4.5 + Math.random() * 0.5, 
    reviews: Math.floor(Math.random() * 5000), 
    stock: Math.floor(Math.random() * 50) + 5 
  },
  { 
    id: 'j37', 
    name: 'jordan-air-jordan-5-fire', 
    brand: 'Jordan', 
    price: Math.floor(Math.random() * (20000 - 6000) + 6000), 
    originalPrice: Math.floor(Math.random() * (25000 - 8000) + 8000), 
    image: 'https://res.cloudinary.com/des0lvjl7/image/upload/v1772206890/sneaker-store/jordan/sneaker-store/jordan/jordan-air-jordan-5-fire.png', 
    description: 'Premium Jordan sneaker', 
    category: 'Lifestyle', 
    gender: 'Unisex', 
    colors: ['Default'], 
    sizes: [6, 7, 8, 9, 10, 11], 
    rating: 4.5 + Math.random() * 0.5, 
    reviews: Math.floor(Math.random() * 5000), 
    stock: Math.floor(Math.random() * 50) + 5 
  },
  { 
    id: 'j38', 
    name: 'jordan-jumpman-mvp', 
    brand: 'Jordan', 
    price: Math.floor(Math.random() * (20000 - 6000) + 6000), 
    originalPrice: Math.floor(Math.random() * (25000 - 8000) + 8000), 
    image: 'https://res.cloudinary.com/des0lvjl7/image/upload/v1772206891/sneaker-store/jordan/sneaker-store/jordan/jordan-jumpman-mvp.jpg', 
    description: 'Premium Jordan sneaker', 
    category: 'Lifestyle', 
    gender: 'Unisex', 
    colors: ['Default'], 
    sizes: [6, 7, 8, 9, 10, 11], 
    rating: 4.5 + Math.random() * 0.5, 
    reviews: Math.floor(Math.random() * 5000), 
    stock: Math.floor(Math.random() * 50) + 5 
  },
  { 
    id: 'j39', 
    name: 'jordan-spizike-low', 
    brand: 'Jordan', 
    price: Math.floor(Math.random() * (20000 - 6000) + 6000), 
    originalPrice: Math.floor(Math.random() * (25000 - 8000) + 8000), 
    image: 'https://res.cloudinary.com/des0lvjl7/image/upload/v1772206892/sneaker-store/jordan/sneaker-store/jordan/jordan-spizike-low.jpg', 
    description: 'Premium Jordan sneaker', 
    category: 'Lifestyle', 
    gender: 'Unisex', 
    colors: ['Default'], 
    sizes: [6, 7, 8, 9, 10, 11], 
    rating: 4.5 + Math.random() * 0.5, 
    reviews: Math.floor(Math.random() * 5000), 
    stock: Math.floor(Math.random() * 50) + 5 
  },
  { 
    id: 'j40', 
    name: 'jordan-stadium-90', 
    brand: 'Jordan', 
    price: Math.floor(Math.random() * (20000 - 6000) + 6000), 
    originalPrice: Math.floor(Math.random() * (25000 - 8000) + 8000), 
    image: 'https://res.cloudinary.com/des0lvjl7/image/upload/v1772206893/sneaker-store/jordan/sneaker-store/jordan/jordan-stadium-90.jpg', 
    description: 'Premium Jordan sneaker', 
    category: 'Lifestyle', 
    gender: 'Unisex', 
    colors: ['Default'], 
    sizes: [6, 7, 8, 9, 10, 11], 
    rating: 4.5 + Math.random() * 0.5, 
    reviews: Math.floor(Math.random() * 5000), 
    stock: Math.floor(Math.random() * 50) + 5 
  },

  // --- NEW BALANCE (10) ---
  { 
    id: 'n41', 
    name: '1906r-technical', 
    brand: 'New Balance', 
    price: Math.floor(Math.random() * (20000 - 6000) + 6000), 
    originalPrice: Math.floor(Math.random() * (25000 - 8000) + 8000), 
    image: 'https://res.cloudinary.com/des0lvjl7/image/upload/v1772206894/sneaker-store/new-balance/sneaker-store/new-balance/1906r-technical.jpg', 
    description: 'Premium New Balance sneaker', 
    category: 'Lifestyle', 
    gender: 'Unisex', 
    colors: ['Default'], 
    sizes: [6, 7, 8, 9, 10, 11], 
    rating: 4.5 + Math.random() * 0.5, 
    reviews: Math.floor(Math.random() * 5000), 
    stock: Math.floor(Math.random() * 50) + 5 
  },
  { 
    id: 'n42', 
    name: '2002r-phantom', 
    brand: 'New Balance', 
    price: Math.floor(Math.random() * (20000 - 6000) + 6000), 
    originalPrice: Math.floor(Math.random() * (25000 - 8000) + 8000), 
    image: 'https://res.cloudinary.com/des0lvjl7/image/upload/v1772206895/sneaker-store/new-balance/sneaker-store/new-balance/2002r-phantom.jpg', 
    description: 'Premium New Balance sneaker', 
    category: 'Lifestyle', 
    gender: 'Unisex', 
    colors: ['Default'], 
    sizes: [6, 7, 8, 9, 10, 11], 
    rating: 4.5 + Math.random() * 0.5, 
    reviews: Math.floor(Math.random() * 5000), 
    stock: Math.floor(Math.random() * 50) + 5 
  },
  { 
    id: 'n43', 
    name: '530-retro-runner', 
    brand: 'New Balance', 
    price: Math.floor(Math.random() * (20000 - 6000) + 6000), 
    originalPrice: Math.floor(Math.random() * (25000 - 8000) + 8000), 
    image: 'https://res.cloudinary.com/des0lvjl7/image/upload/v1772206896/sneaker-store/new-balance/sneaker-store/new-balance/530-retro-runner.jpg', 
    description: 'Premium New Balance sneaker', 
    category: 'Lifestyle', 
    gender: 'Unisex', 
    colors: ['Default'], 
    sizes: [6, 7, 8, 9, 10, 11], 
    rating: 4.5 + Math.random() * 0.5, 
    reviews: Math.floor(Math.random() * 5000), 
    stock: Math.floor(Math.random() * 50) + 5 
  },
  { 
    id: 'n44', 
    name: '550-white-green', 
    brand: 'New Balance', 
    price: Math.floor(Math.random() * (20000 - 6000) + 6000), 
    originalPrice: Math.floor(Math.random() * (25000 - 8000) + 8000), 
    image: 'https://res.cloudinary.com/des0lvjl7/image/upload/v1772206897/sneaker-store/new-balance/sneaker-store/new-balance/550-white-green.jpg', 
    description: 'Premium New Balance sneaker', 
    category: 'Lifestyle', 
    gender: 'Unisex', 
    colors: ['Default'], 
    sizes: [6, 7, 8, 9, 10, 11], 
    rating: 4.5 + Math.random() * 0.5, 
    reviews: Math.floor(Math.random() * 5000), 
    stock: Math.floor(Math.random() * 50) + 5 
  },
  { 
    id: 'n45', 
    name: '9060-sea-salt', 
    brand: 'New Balance', 
    price: Math.floor(Math.random() * (20000 - 6000) + 6000), 
    originalPrice: Math.floor(Math.random() * (25000 - 8000) + 8000), 
    image: 'https://res.cloudinary.com/des0lvjl7/image/upload/v1772206898/sneaker-store/new-balance/sneaker-store/new-balance/9060-sea-salt.jpg', 
    description: 'Premium New Balance sneaker', 
    category: 'Lifestyle', 
    gender: 'Unisex', 
    colors: ['Default'], 
    sizes: [6, 7, 8, 9, 10, 11], 
    rating: 4.5 + Math.random() * 0.5, 
    reviews: Math.floor(Math.random() * 5000), 
    stock: Math.floor(Math.random() * 50) + 5 
  },
  { 
    id: 'n46', 
    name: '991v2-slate', 
    brand: 'New Balance', 
    price: Math.floor(Math.random() * (20000 - 6000) + 6000), 
    originalPrice: Math.floor(Math.random() * (25000 - 8000) + 8000), 
    image: 'https://res.cloudinary.com/des0lvjl7/image/upload/v1772206900/sneaker-store/new-balance/sneaker-store/new-balance/991v2-slate.jpg', 
    description: 'Premium New Balance sneaker', 
    category: 'Lifestyle', 
    gender: 'Unisex', 
    colors: ['Default'], 
    sizes: [6, 7, 8, 9, 10, 11], 
    rating: 4.5 + Math.random() * 0.5, 
    reviews: Math.floor(Math.random() * 5000), 
    stock: Math.floor(Math.random() * 50) + 5 
  },
  { 
    id: 'n47', 
    name: 'ct302-platform', 
    brand: 'New Balance', 
    price: Math.floor(Math.random() * (20000 - 6000) + 6000), 
    originalPrice: Math.floor(Math.random() * (25000 - 8000) + 8000), 
    image: 'https://res.cloudinary.com/des0lvjl7/image/upload/v1772206901/sneaker-store/new-balance/sneaker-store/new-balance/ct302-platform.jpg', 
    description: 'Premium New Balance sneaker', 
    category: 'Lifestyle', 
    gender: 'Unisex', 
    colors: ['Default'], 
    sizes: [6, 7, 8, 9, 10, 11], 
    rating: 4.5 + Math.random() * 0.5, 
    reviews: Math.floor(Math.random() * 5000), 
    stock: Math.floor(Math.random() * 50) + 5 
  },
  { 
    id: 'n48', 
    name: 'freash-foam-1080', 
    brand: 'New Balance', 
    price: Math.floor(Math.random() * (20000 - 6000) + 6000), 
    originalPrice: Math.floor(Math.random() * (25000 - 8000) + 8000), 
    image: 'https://res.cloudinary.com/des0lvjl7/image/upload/v1772206902/sneaker-store/new-balance/sneaker-store/new-balance/freash-foam-1080.jpg', 
    description: 'Premium New Balance sneaker', 
    category: 'Lifestyle', 
    gender: 'Unisex', 
    colors: ['Default'], 
    sizes: [6, 7, 8, 9, 10, 11], 
    rating: 4.5 + Math.random() * 0.5, 
    reviews: Math.floor(Math.random() * 5000), 
    stock: Math.floor(Math.random() * 50) + 5 
  },
  { 
    id: 'n49', 
    name: 'freash-foam-1080', 
    brand: 'New Balance', 
    price: Math.floor(Math.random() * (20000 - 6000) + 6000), 
    originalPrice: Math.floor(Math.random() * (25000 - 8000) + 8000), 
    image: 'https://res.cloudinary.com/des0lvjl7/image/upload/v1772206903/sneaker-store/new-balance/sneaker-store/new-balance/freash-foam-1080.jpg', 
    description: 'Premium New Balance sneaker', 
    category: 'Lifestyle', 
    gender: 'Unisex', 
    colors: ['Default'], 
    sizes: [6, 7, 8, 9, 10, 11], 
    rating: 4.5 + Math.random() * 0.5, 
    reviews: Math.floor(Math.random() * 5000), 
    stock: Math.floor(Math.random() * 50) + 5 
  },
  { 
    id: 'n50', 
    name: 'fuelcell-elite', 
    brand: 'New Balance', 
    price: Math.floor(Math.random() * (20000 - 6000) + 6000), 
    originalPrice: Math.floor(Math.random() * (25000 - 8000) + 8000), 
    image: 'https://res.cloudinary.com/des0lvjl7/image/upload/v1772206904/sneaker-store/new-balance/sneaker-store/new-balance/fuelcell-elite.jpg', 
    description: 'Premium New Balance sneaker', 
    category: 'Lifestyle', 
    gender: 'Unisex', 
    colors: ['Default'], 
    sizes: [6, 7, 8, 9, 10, 11], 
    rating: 4.5 + Math.random() * 0.5, 
    reviews: Math.floor(Math.random() * 5000), 
    stock: Math.floor(Math.random() * 50) + 5 
  },

  // --- PUMA (10) ---
  { 
    id: 'p51', 
    name: 'puma-lafrance-melo', 
    brand: 'Puma', 
    price: Math.floor(Math.random() * (20000 - 6000) + 6000), 
    originalPrice: Math.floor(Math.random() * (25000 - 8000) + 8000), 
    image: 'https://res.cloudinary.com/des0lvjl7/image/upload/v1772206905/sneaker-store/puma/sneaker-store/puma/puma-lafrance-melo.jpg', 
    description: 'Premium Puma sneaker', 
    category: 'Lifestyle', 
    gender: 'Unisex', 
    colors: ['Default'], 
    sizes: [6, 7, 8, 9, 10, 11], 
    rating: 4.5 + Math.random() * 0.5, 
    reviews: Math.floor(Math.random() * 5000), 
    stock: Math.floor(Math.random() * 50) + 5 
  },
  { 
    id: 'p52', 
    name: 'puma-mayze-platform', 
    brand: 'Puma', 
    price: Math.floor(Math.random() * (20000 - 6000) + 6000), 
    originalPrice: Math.floor(Math.random() * (25000 - 8000) + 8000), 
    image: 'https://res.cloudinary.com/des0lvjl7/image/upload/v1772206906/sneaker-store/puma/sneaker-store/puma/puma-mayze-platform.jpg', 
    description: 'Premium Puma sneaker', 
    category: 'Lifestyle', 
    gender: 'Unisex', 
    colors: ['Default'], 
    sizes: [6, 7, 8, 9, 10, 11], 
    rating: 4.5 + Math.random() * 0.5, 
    reviews: Math.floor(Math.random() * 5000), 
    stock: Math.floor(Math.random() * 50) + 5 
  },
  { 
    id: 'p53', 
    name: 'puma-nitro-2', 
    brand: 'Puma', 
    price: Math.floor(Math.random() * (20000 - 6000) + 6000), 
    originalPrice: Math.floor(Math.random() * (25000 - 8000) + 8000), 
    image: 'https://res.cloudinary.com/des0lvjl7/image/upload/v1772206907/sneaker-store/puma/sneaker-store/puma/puma-nitro-2.jpg', 
    description: 'Premium Puma sneaker', 
    category: 'Lifestyle', 
    gender: 'Unisex', 
    colors: ['Default'], 
    sizes: [6, 7, 8, 9, 10, 11], 
    rating: 4.5 + Math.random() * 0.5, 
    reviews: Math.floor(Math.random() * 5000), 
    stock: Math.floor(Math.random() * 50) + 5 
  },
  { 
    id: 'p54', 
    name: 'puma-og-blue', 
    brand: 'Puma', 
    price: Math.floor(Math.random() * (20000 - 6000) + 6000), 
    originalPrice: Math.floor(Math.random() * (25000 - 8000) + 8000), 
    image: 'https://res.cloudinary.com/des0lvjl7/image/upload/v1772206908/sneaker-store/puma/sneaker-store/puma/puma-og-blue.jpg', 
    description: 'Premium Puma sneaker', 
    category: 'Lifestyle', 
    gender: 'Unisex', 
    colors: ['Default'], 
    sizes: [6, 7, 8, 9, 10, 11], 
    rating: 4.5 + Math.random() * 0.5, 
    reviews: Math.floor(Math.random() * 5000), 
    stock: Math.floor(Math.random() * 50) + 5 
  },
  { 
    id: 'p55', 
    name: 'puma-palmero-leather', 
    brand: 'Puma', 
    price: Math.floor(Math.random() * (20000 - 6000) + 6000), 
    originalPrice: Math.floor(Math.random() * (25000 - 8000) + 8000), 
    image: 'https://res.cloudinary.com/des0lvjl7/image/upload/v1772206909/sneaker-store/puma/sneaker-store/puma/puma-palmero-leather.jpg', 
    description: 'Premium Puma sneaker', 
    category: 'Lifestyle', 
    gender: 'Unisex', 
    colors: ['Default'], 
    sizes: [6, 7, 8, 9, 10, 11], 
    rating: 4.5 + Math.random() * 0.5, 
    reviews: Math.floor(Math.random() * 5000), 
    stock: Math.floor(Math.random() * 50) + 5 
  },
  { 
    id: 'p56', 
    name: 'puma-rx-effect', 
    brand: 'Puma', 
    price: Math.floor(Math.random() * (20000 - 6000) + 6000), 
    originalPrice: Math.floor(Math.random() * (25000 - 8000) + 8000), 
    image: 'https://res.cloudinary.com/des0lvjl7/image/upload/v1772206910/sneaker-store/puma/sneaker-store/puma/puma-rx-effect.jpg', 
    description: 'Premium Puma sneaker', 
    category: 'Lifestyle', 
    gender: 'Unisex', 
    colors: ['Default'], 
    sizes: [6, 7, 8, 9, 10, 11], 
    rating: 4.5 + Math.random() * 0.5, 
    reviews: Math.floor(Math.random() * 5000), 
    stock: Math.floor(Math.random() * 50) + 5 
  },
  { 
    id: 'p57', 
    name: 'puma-slipstream-retro', 
    brand: 'Puma', 
    price: Math.floor(Math.random() * (20000 - 6000) + 6000), 
    originalPrice: Math.floor(Math.random() * (25000 - 8000) + 8000), 
    image: 'https://res.cloudinary.com/des0lvjl7/image/upload/v1772206911/sneaker-store/puma/sneaker-store/puma/puma-slipstream-retro.jpg', 
    description: 'Premium Puma sneaker', 
    category: 'Lifestyle', 
    gender: 'Unisex', 
    colors: ['Default'], 
    sizes: [6, 7, 8, 9, 10, 11], 
    rating: 4.5 + Math.random() * 0.5, 
    reviews: Math.floor(Math.random() * 5000), 
    stock: Math.floor(Math.random() * 50) + 5 
  },
  { 
    id: 'p58', 
    name: 'puma-suede-classic', 
    brand: 'Puma', 
    price: Math.floor(Math.random() * (20000 - 6000) + 6000), 
    originalPrice: Math.floor(Math.random() * (25000 - 8000) + 8000), 
    image: 'https://res.cloudinary.com/des0lvjl7/image/upload/v1772206912/sneaker-store/puma/sneaker-store/puma/puma-suede-classic.jpg', 
    description: 'Premium Puma sneaker', 
    category: 'Lifestyle', 
    gender: 'Unisex', 
    colors: ['Default'], 
    sizes: [6, 7, 8, 9, 10, 11], 
    rating: 4.5 + Math.random() * 0.5, 
    reviews: Math.floor(Math.random() * 5000), 
    stock: Math.floor(Math.random() * 50) + 5 
  },
  { 
    id: 'p59', 
    name: 'puma-super-team-navvy', 
    brand: 'Puma', 
    price: Math.floor(Math.random() * (20000 - 6000) + 6000), 
    originalPrice: Math.floor(Math.random() * (25000 - 8000) + 8000), 
    image: 'https://res.cloudinary.com/des0lvjl7/image/upload/v1772206913/sneaker-store/puma/sneaker-store/puma/puma-super-team-navvy.jpg', 
    description: 'Premium Puma sneaker', 
    category: 'Lifestyle', 
    gender: 'Unisex', 
    colors: ['Default'], 
    sizes: [6, 7, 8, 9, 10, 11], 
    rating: 4.5 + Math.random() * 0.5, 
    reviews: Math.floor(Math.random() * 5000), 
    stock: Math.floor(Math.random() * 50) + 5 
  },
  { 
    id: 'p60', 
    name: 'puma-velophasis-silver', 
    brand: 'Puma', 
    price: Math.floor(Math.random() * (20000 - 6000) + 6000), 
    originalPrice: Math.floor(Math.random() * (25000 - 8000) + 8000), 
    image: 'https://res.cloudinary.com/des0lvjl7/image/upload/v1772206914/sneaker-store/puma/sneaker-store/puma/puma-velophasis-silver.jpg', 
    description: 'Premium Puma sneaker', 
    category: 'Lifestyle', 
    gender: 'Unisex', 
    colors: ['Default'], 
    sizes: [6, 7, 8, 9, 10, 11], 
    rating: 4.5 + Math.random() * 0.5, 
    reviews: Math.floor(Math.random() * 5000), 
    stock: Math.floor(Math.random() * 50) + 5 
  },
];
